import { Vehicle } from './types';

export const VEHICLES: Vehicle[] = [
  {
    id: '1',
    name: 'Tesla Model S Plaid',
    type: 'Luxury',
    pricePerDay: 250,
    image: 'https://picsum.photos/id/111/800/500', 
    specs: { seats: 5, transmission: 'Auto', fuel: 'Electric', range: '396 mi' },
    rating: 4.9,
    available: true,
  },
  {
    id: '2',
    name: 'Ford Mustang GT',
    type: 'Car',
    pricePerDay: 120,
    image: 'https://picsum.photos/id/133/800/500',
    specs: { seats: 4, transmission: 'Manual', fuel: 'Petrol' },
    rating: 4.7,
    available: true,
  },
  {
    id: '3',
    name: 'Harley Davidson Iron 883',
    type: 'Bike',
    pricePerDay: 90,
    image: 'https://picsum.photos/id/146/800/500',
    specs: { seats: 1, transmission: 'Manual', fuel: 'Petrol' },
    rating: 4.8,
    available: true,
  },
  {
    id: '4',
    name: 'Range Rover Sport',
    type: 'SUV',
    pricePerDay: 180,
    image: 'https://picsum.photos/id/183/800/500',
    specs: { seats: 7, transmission: 'Auto', fuel: 'Diesel' },
    rating: 4.6,
    available: false,
  },
  {
    id: '5',
    name: 'Ducati Panigale V4',
    type: 'Bike',
    pricePerDay: 200,
    image: 'https://picsum.photos/id/191/800/500',
    specs: { seats: 1, transmission: 'Manual', fuel: 'Petrol' },
    rating: 5.0,
    available: true,
  },
  {
    id: '6',
    name: 'Mercedes-Benz Sprinter',
    type: 'Van',
    pricePerDay: 140,
    image: 'https://picsum.photos/id/296/800/500',
    specs: { seats: 12, transmission: 'Auto', fuel: 'Diesel' },
    rating: 4.5,
    available: true,
  },
];
